# GitLeaks Configuration for DataPrism
# This configuration excludes false positives and example patterns from security scanning

title = "DataPrism GitLeaks Configuration"

[extend]
# Use default rules and add allowlist
useDefault = true

[allowlist]
description = "Allowlist for DataPrism documentation and examples"
paths = [
  '''docs/.*\.md''',
  '''examples/.*''',
  '''tests/.*''',
  '''.*mock.*''',
  '''.*\.config\.(js|ts|json)''',
  '''package(-lock)?\.json''',
  '''\.gitleaks\.toml''',
  '''README\.md''',
  '''CHANGELOG\.md''',
  '''\.github/.*''',
  '''apps/demo-analytics/src/contexts/MockDataPrismContext\.tsx'''
]

[[allowlist.rules]]
description = "Slack webhook URL examples in documentation"
regex = '''hooks\.slack\.com/services/T00000000/B00000000/\[TOKEN_HERE\]'''

[[allowlist.rules]]
description = "Example webhook URLs in documentation"
regex = '''https://hooks\.slack\.com/services/T00000000/B00000000/\[TOKEN_HERE\]'''

[[allowlist.rules]]
description = "Generic placeholder tokens in documentation"
regex = '''\[TOKEN_HERE\]'''

[[allowlist.rules]]
description = "Documentation example patterns"
regex = '''YOUR_WEBHOOK_URL'''

[[allowlist.rules]]
description = "Generic API key placeholders"
regex = '''YOUR_API_KEY'''

[[allowlist.rules]]
description = "Generic secret placeholders"
regex = '''YOUR_SECRET'''

[[allowlist.rules]]
description = "Example commit SHAs"
regex = '''a1b2c3d'''

[[allowlist.rules]]
description = "Test data and mock values"
regex = '''test-secret-key'''

[[allowlist.rules]]
description = "Documentation file extensions"
regex = '''\.md$'''